### PR TITLE
Update the blog post link by Aaron Lee

### PR DESCRIPTION
**Pull request by Sk7w4tch3r**

### CODE REVIEW

**Comment by a3f** [comment]
Thanks for your PR. I think it would be better to link at the archive.org link instead: https://web.archive.org/web/20001210152800/http://www.gamasutra.com/features/20000908/lee_01.htm for future proofness.

What do you think?

**Comment by Sk7w4tch3r** [comment]
The current version is more detailed comparing to the previous version that you sent. I suggest using the link to the latest update from archive.org 
[https://web.archive.org/web/20220630134938/https://www.gamedeveloper.com/programming/building-your-own-subdivision-surfaces](https://web.archive.org/web/20220630134938/https://www.gamedeveloper.com/programming/building-your-own-subdivision-surfaces)

**Comment by a3f** [comment]
How is it more detailed? On a cursory glance, it just seems the old version was paginated and the new isn't.

**Comment by Sk7w4tch3r** [comment]
Oh, did not see the pagination there. So, perhaps using either makes sense.

**Comment by a3f** [comment]
If you change it to archive.org for the old link that would be best IMO. Could you do that? Thanks.

**Comment by Sk7w4tch3r** [comment]
Ok, I'm closing this PR and openning a new one.

**Pull request closed without merging**
